sudo: false
language: node_js
node_js:
 - "0.10"
notifications:
  irc:
    channels:
      - "irc.mozilla.org#payments"
    on_success: change
    on_failure: always
install:
  - "npm install"
before_script:
   - git clone -q git://github.com/n1k0/casperjs.git
   - cd casperjs; git checkout -q tags/1.1-beta3; cd ../
   - export PATH=$PATH:`pwd`/casperjs/bin
   - phantomjs --version; casperjs --version
script:
  - "npm test"
  - "npm run-script uitest"
